<?php

namespace AppBundle\Repository;

/**
 * IssueTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IssueTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
