<?php

namespace AppBundle\Repository;

/**
 * IssueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IssueRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $page
     * @param $limit
     * @return \Doctrine\ORM\Query
     */
    public function findWithPagination($page, $limit)
    {
        return $this->createQueryBuilder('i')
            ->getQuery();
    }
}
