<?php

namespace AppBundle\Repository;

/**
 * IssueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IssueRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return \Doctrine\ORM\Query
     */
    public function findAllWithPagination()
    {
        return $this->createQueryBuilder('i')
            ->getQuery();
    }
}
