<?php

namespace AppBundle\Repository;

/**
 * VersionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VersionRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return array
     */
    public function getTimespentByVersion(){
        $qb = $this->createQueryBuilder('v');
        $qb->select('v.name', 'sum(w.timeSpent * s.costPerHour) as cost');
        $qb->leftJoin('v.issues', 'i');
        $qb->leftJoin('i.worklogs', 'w');
        $qb->leftJoin('w.employee', 'e');
        $qb->leftJoin('e.salaries', 's');
        $qb->where('MONTH(w.date) = s.month');
        $qb->andWhere('YEAR(w.date) = s.year');
        $qb->groupBy('v.name');
        $query = $qb->getQuery();

        return $query->getResult();
    }
}
